# Generated by Django 2.1.5 on 2022-01-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='person_id',
            field=models.IntegerField(default=0, verbose_name='Criminal Number'),
        ),
    ]
