# Generated by Django 2.1.5 on 2022-01-13 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subadmin', '0004_auto_20220101_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='user',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
