# Generated by Django 2.1.5 on 2022-01-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='email',
        ),
    ]
