# Generated by Django 2.1.5 on 2022-01-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_station_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Place'),
        ),
    ]
