# Generated by Django 2.1.5 on 2022-01-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220101_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.State')),
            ],
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.RemoveField(
            model_name='place',
            name='district',
        ),
        migrations.RemoveField(
            model_name='station',
            name='place',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.City'),
        ),
    ]
