# Generated by Django 2.1.5 on 2022-01-01 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220101_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='station',
            name='subadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Officer'),
        ),
    ]
