# Generated by Django 2.1.5 on 2022-01-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0003_imagesearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesearch',
            name='image',
            field=models.FileField(max_length=300, upload_to='Temp', verbose_name='Choose an Image'),
        ),
    ]
